/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sg.blogsite.dao;

import com.sg.blogsite.model.Blog;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author apprentice
 */
public class BlogDaoDbStubImpl implements BlogDao {

    private Blog onlyBlog;
    private List<Blog> blogList = new ArrayList<>();

    public BlogDaoDbStubImpl() {
        onlyBlog = new Blog();
        onlyBlog.setBlogPublished(Boolean.FALSE);
        onlyBlog.setBlogDatePublished(LocalDate.now());
        onlyBlog.setBlogTitle("Blog Title");
        onlyBlog.setBlogArticle("this is the blog artical");

        blogList.add(onlyBlog);

    }

    @Override
    public Blog createBlog(Blog blog) {
        if (blog.getBlogTitle().equals(onlyBlog.getBlogTitle())) {
            return onlyBlog;
        } else {
            return null;
        }
    }

    @Override
    public void updateBlog(Blog blog) {
    }

    @Override
    public Blog readBlog(int blogId) {
        if (blogId == onlyBlog.getBlogId()) {  //may have to swap this with null due to autogenerated ids
            return onlyBlog;
        } else {
            return null;
        }
    }

    public List<Blog> getLastFiveBlogs() {
        return blogList;
    }

    @Override
    public List<Blog> getAllBlogsByCategory(int categoryId) {
        return blogList;
    }
}
