/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sg.blogsite.dao;

import com.sg.blogsite.model.Blog;

/**
 *
 * @author apprentice
 */
public class BlogDaoDbStubImpl {

    private Blog onlyBlog;
    private List<Blog> blogList = new ArrayList<>();

    public BlogDaoSDbtubImpl() {
        onlyBlog = new Blog();
        onlyBlog.setBlogPublished("True");
        onlyBlog.set("stub testing addHero");
        onlyHero.setSuperpower("no super powers here");

        heroList.add(onlyHero);

    }

    @Override
    public Hero addHero(Hero hero) {
        if (hero.getName().equals(onlyHero.getName())) {
            return onlyHero;
        } else {
            return null;
        }
    }

    @Override
    public void deleteHero(int idHero) {

    }

    @Override
    public void updateHero(Hero hero) {

    }

    @Override
    public Hero getHeroById(int idHero) {
        if (idHero == onlyHero.getIdHero()) {  //may have to swap this with null due to autogenerated ids
            return onlyHero;
        } else {
            return null;
        }
    }

    @Override
    public List<Hero> getAllHeros() {
        return heroList;
    }
}
